In [831]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [832]:
# загрузка данных
df = pd.read_excel("price1.xlsx")
df

   area  price
0    28    3.1
1    42    3.8
2    45    3.9
3    52    4.4
4    56    4.5
5    68    5.9
6    70    5.6
7    75    6.4
8    90    7.3

In [833]:
X_train = df["area"]  # Преобразуем X в двумерный массив (n_samples, 1)
y_train = df["price"]

In [834]:
model = tf.keras.Sequential([
    Input(shape=(1,)),
    Dense(100) # из-за количества нейронов меняется количество выводимых данных - если хотим что ыб количество точно соответствовало начальынм данным нужно указать количество нейронов как 1
])

In [835]:
model.compile(optimizer="sgd", loss="mean_squared_error")

In [836]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 109.5461
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 7.0356
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5375
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1256
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0994
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0978
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0977
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0977
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0977
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0977

In [837]:
model.summary()

Model: "sequential_93"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_73 (Dense)                │ (None, 100)            │           200 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 202 (812.00 B)

 Trainable params: 200 (800.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [838]:
m = model.predict(X)[:, 0] # берем только первый столбец
m = pd.DataFrame(m)
m # предсказываем на основе наших данных

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

          0
0  2.357817
1  3.535471
2  3.787826
3  4.376652
4  4.713125
5  5.722542
6  5.890779
7  6.311369
8  7.573141

In [839]:
pred = pd.read_excel("prediction_price.xlsx")
pred

    area
0     25
1     37
2     40
3     58
4     61
5     67
6     72
7     85
8     96
9    105
10   118

In [840]:
s = model.predict(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

In [841]:
pred["pred"] = s[:, 0] # берем только первый столбец
pred

    area      pred
0     25  2.105463
1     37  3.114881
2     40  3.367235
3     58  4.881361
4     61  5.133716
5     67  5.638424
6     72  6.059015
7     85  7.152550
8     96  8.077849
9    105  8.834912
10   118  9.928449